<?php

 $_USERS = array (
  0 => 
  array (
    'name' => 'admin',
    'pass' => '$1$ktIOQzt6$VUyJLIV83oZmWE0O1B3cf1',
    'role' => 'superadmin',
    'email' => '12312312312',
  ),
  1 => 
  array (
    'name' => 'Alan',
    'isStudent' => '是',
    'pass' => '$1$eWTccPWH$xTDq7egGPdclvmyPWRuA90',
    'email' => '18229952930',
    'schoolName' => '长理',
    'academyName' => '计通',
    'majorName' => '计科',
    'role' => 'superadmin',
    'dir' => '["Alan"]',
    'quota' => '100',
  ),
  3 => 
  array (
    'isStudent' => '否',
    'name' => 'sofia111',
    'pass' => '$1$h4FwtByZ$/3KYnL2lqc9mHOvbyvwiV0',
    'email' => '18670379836',
    'role' => 'user',
    'dir' => '["sofia111"]',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'quota' => '100',
  ),
  4 => 
  array (
    'name' => 'looyeagee',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$F7waTGDt$XXpOoLNFputAPpBi82JwE.',
    'email' => '66666',
    'role' => 'user',
    'dir' => '["looyeagee"]',
    'quota' => '1000',
  ),
  7 => 
  array (
    'name' => 'qwe',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$0LZJG161$VZyeBwVPByB.9b6AmUe.L1',
    'email' => '17388939290',
    'role' => 'user',
    'dir' => '["qwe"]',
    'quota' => '100',
  ),
  9 => 
  array (
    'name' => 'klk165416541654',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$JKXvuh54$Lyx625WPpFG8IySyGMTrr0',
    'email' => '15729411901',
    'role' => 'user',
    'dir' => '["klk165416541654"]',
    'quota' => '100',
  ),
  10 => 
  array (
    'name' => 'xzjj',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$p0vNyyGU$p5tXsqCmAqO1CpvJ1ocCT0',
    'email' => '15115446117',
    'role' => 'user',
    'dir' => '["xzjj"]',
    'quota' => '100',
  ),
  11 => 
  array (
    'name' => 'Asdd',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '人力资源管理',
    'pass' => '$1$A5eow9Wp$Bkq5eUWvcvIHB/OqvQc8q.',
    'email' => '13187212409',
    'role' => 'user',
    'dir' => '["Asdd"]',
    'quota' => '100',
  ),
  12 => 
  array (
    'name' => 'kittyche',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学（ACCA）',
    'pass' => '$1$03lJFdck$Q0U1xvgn1WEZ1b/293hYB1',
    'email' => '15274790662',
    'role' => 'user',
    'dir' => '["kittyche"]',
    'quota' => '100',
  ),
  13 => 
  array (
    'name' => '我的啊',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '能源与动力工程学院',
    'majorName' => '新能源科学与工程',
    'pass' => '$1$R2NeC8qh$HPGEdIxRcXVZyweH98/dS/',
    'email' => '13467905770',
    'role' => 'user',
    'dir' => '["\\u6211\\u7684\\u554a"]',
    'quota' => '100',
  ),
  14 => 
  array (
    'name' => 'sjr1478',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$W7VlxFkt$GB6m/vqlMduBWZxRLtZRp.',
    'email' => '18110386211',
    'role' => 'user',
    'dir' => '["sjr1478"]',
    'quota' => '100',
  ),
  15 => 
  array (
    'name' => 'lsx12138',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '港口航道与海岸工程',
    'pass' => '$1$8bOH2hZ4$u.MZCpmaBkV0LriBRWS1n0',
    'email' => '18711151412',
    'role' => 'user',
    'dir' => '["lsx12138"]',
    'quota' => '100',
  ),
  16 => 
  array (
    'name' => 'wll',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$8o3hTI51$OSQKt0hxm/6MYMQKPZ7tD1',
    'email' => '17809501899',
    'role' => 'user',
    'dir' => '["wll"]',
    'quota' => '100',
  ),
  17 => 
  array (
    'name' => 'zeng',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '计算机科学与技术',
    'pass' => '$1$wS2H59VV$QhE8VmjFBf68rtp2f96Yg0',
    'email' => '18100738792',
    'role' => 'user',
    'dir' => '["zeng"]',
    'quota' => '100',
  ),
  18 => 
  array (
    'name' => 'taozi',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$8AvshdDt$QuKfMUM9wazS5AAJNoPEN/',
    'email' => '15308723640',
    'role' => 'user',
    'dir' => '["taozi"]',
    'quota' => '100',
  ),
  19 => 
  array (
    'name' => '袁伟',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$1X0uZxJF$t6h1IpS2Fhd8oldmH4FbY0',
    'email' => '15652933625',
    'role' => 'user',
    'dir' => '["\\u8881\\u4f1f"]',
    'quota' => '100',
  ),
  20 => 
  array (
    'name' => 'abc187',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '国际经济与贸易',
    'pass' => '$1$KTxrxxPs$5E3jCbE60J2t1zfXuw6W71',
    'email' => '18390955759',
    'role' => 'user',
    'dir' => '["abc187"]',
    'quota' => '100',
  ),
  22 => 
  array (
    'name' => 'Eudora',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '物理学',
    'pass' => '$1$fjo91Mr0$yeKU63uIYfa0F4jrunDDV0',
    'email' => '15116286492',
    'role' => 'user',
    'dir' => '["Eudora"]',
    'quota' => '100',
  ),
  23 => 
  array (
    'name' => 'pengjie123',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化',
    'pass' => '$1$oz40xZ5D$V2LRe.9c73pvHWxinCg3j/',
    'email' => '17711621241',
    'role' => 'user',
    'dir' => '["pengjie123"]',
    'quota' => '100',
  ),
  24 => 
  array (
    'name' => 'YMQ',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '国际经济与贸易',
    'pass' => '$1$0faWwksS$vK8LHezxOBhPUXXu0rCDQ/',
    'email' => '18900744470',
    'role' => 'user',
    'dir' => '["YMQ"]',
    'quota' => '100',
  ),
  25 => 
  array (
    'name' => '陈昭亮',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '物流工程',
    'pass' => '$1$zUSUdEWv$QnokZiaScZKSOoH5fkR.a.',
    'email' => '13548759131',
    'role' => 'user',
    'dir' => '["\\u9648\\u662d\\u4eae"]',
    'quota' => '100',
  ),
  26 => 
  array (
    'name' => 'Tp879626',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$GSAiB3TS$.pP4ue1RJG3To5sEP/YNy/',
    'email' => '18390267906',
    'role' => 'user',
    'dir' => '["Tp879626"]',
    'quota' => '100',
  ),
  27 => 
  array (
    'name' => 'PQTL',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$9BwXfgX7$/cGHaoTZxaNAkUAvm4OPW1',
    'email' => '15367482235',
    'role' => 'user',
    'dir' => '["PQTL"]',
    'quota' => '100',
  ),
  28 => 
  array (
    'name' => 'aab水煮白菜',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电子信息工程',
    'pass' => '$1$peAZ3fQm$2UzSo44rH.SNZ9p8hobLL1',
    'email' => '18774859665',
    'role' => 'user',
    'dir' => '["aab\\u6c34\\u716e\\u767d\\u83dc"]',
    'quota' => '100',
  ),
  29 => 
  array (
    'name' => 'rainbow',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$9Uzgohf9$gTF7QtREUynFkQqL9DZFA1',
    'email' => '17671468726',
    'role' => 'user',
    'dir' => '["rainbow"]',
    'quota' => '100',
  ),
  31 => 
  array (
    'name' => 'lijiarun',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$VpRoZI2Y$WXPjwi4EfDZT1Jbw9VRAu.',
    'email' => '18508401667',
    'role' => 'user',
    'dir' => '["lijiarun"]',
    'quota' => '100',
  ),
  32 => 
  array (
    'name' => 'houzhouyang',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$q4CMD46y$SaF3ZHnlKuWtLxti51WfU/',
    'email' => '17607610915',
    'role' => 'user',
    'dir' => '["houzhouyang"]',
    'quota' => '100',
  ),
  33 => 
  array (
    'name' => 'wpc069889',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '计算机科学与技术',
    'pass' => '$1$1Pqx5hW6$gHq2Jnp9V9l.pPff3mFBE1',
    'email' => '15211443248',
    'role' => 'user',
    'dir' => '["wpc069889"]',
    'quota' => '100',
  ),
  34 => 
  array (
    'name' => 'liuyufd',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '能源与动力工程学院',
    'majorName' => '自动化(热工过程自动化)',
    'pass' => '$1$9QknMJvF$BViH6jVP.6B9/mA33npOv1',
    'email' => '13037312786',
    'role' => 'user',
    'dir' => '["liuyufd"]',
    'quota' => '100',
  ),
  35 => 
  array (
    'name' => 'plm',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$huZ8zCpj$WN/DW1e97R85dB9gxrPiU.',
    'email' => '15367489790',
    'role' => 'user',
    'dir' => '["plm"]',
    'quota' => '100',
  ),
  36 => 
  array (
    'name' => 'C960471557',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(土建)',
    'pass' => '$1$nglgp506$b/MQFMthpd2Vp289QIDPw1',
    'email' => '17673052558',
    'role' => 'user',
    'dir' => '["C960471557"]',
    'quota' => '100',
  ),
  37 => 
  array (
    'name' => 'zzz',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '交通工程',
    'pass' => '$1$b9v7nvcb$iUbQOwb2yD8F3i2brADRY/',
    'email' => '18373146226',
    'role' => 'user',
    'dir' => '["zzz"]',
    'quota' => '100',
  ),
  38 => 
  array (
    'name' => 'liujunqiang',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化(机电)',
    'pass' => '$1$VwbKhKpO$MKBZWTWhjQ4EGIWWzWm2J1',
    'email' => '18274976641',
    'role' => 'user',
    'dir' => '["liujunqiang"]',
    'quota' => '100',
  ),
  39 => 
  array (
    'name' => 'chen',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$wwAGMCVE$6ygR6G.lzvFvGA0i11e9r1',
    'email' => '13875802105',
    'role' => 'user',
    'dir' => '["chen"]',
    'quota' => '100',
  ),
  40 => 
  array (
    'name' => 'wyl',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '港口航道与海岸工程',
    'pass' => '$1$P6DBYSxt$B4BrA23PIaV5K8RdEDusE.',
    'email' => '15073874813',
    'role' => 'user',
    'dir' => '["wyl"]',
    'quota' => '100',
  ),
  41 => 
  array (
    'name' => 'mmp',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械类',
    'pass' => '$1$64BYF5tQ$4AiNqrtCQlNMoxUiSAZgx1',
    'email' => '13337294289',
    'role' => 'user',
    'dir' => '["mmp"]',
    'quota' => '100',
  ),
  42 => 
  array (
    'name' => 'lk131',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$TJjXbJnu$QkXwfM2naA0VqJ1MrLiy/1',
    'email' => '15308477857',
    'role' => 'user',
    'dir' => '["lk131"]',
    'quota' => '100',
  ),
  43 => 
  array (
    'name' => 'cslgfzj',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '车辆工程',
    'pass' => '$1$bhvrxc62$0rWc2V0sIFlJwbkmKYk4h/',
    'email' => '17742518819',
    'role' => 'user',
    'dir' => '["cslgfzj"]',
    'quota' => '100',
  ),
  44 => 
  array (
    'name' => 'kangkang',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '测绘工程',
    'pass' => '$1$BIstkwL3$qlBn/fZHhIreFrnNBDYgt/',
    'email' => '18692230402',
    'role' => 'user',
    'dir' => '["kangkang"]',
    'quota' => '100',
  ),
  45 => 
  array (
    'name' => 'Lisa',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电子信息工程',
    'pass' => '$1$7Gc1Zk1H$/6uYTKpF9ckeKEzv8EZK61',
    'email' => '18007404794',
    'role' => 'user',
    'dir' => '["Lisa"]',
    'quota' => '100',
  ),
  46 => 
  array (
    'name' => 'zhq',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(隧道与地下工程)',
    'pass' => '$1$tTfBmRr3$vyZ0oUklPIPlygYJ87Sgk/',
    'email' => '18273163871',
    'role' => 'user',
    'dir' => '["zhq"]',
    'quota' => '100',
  ),
  47 => 
  array (
    'name' => '李威',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电子信息工程',
    'pass' => '$1$v5Low0kf$bDiP1sl6Qm0Ktd2wVnT9Z/',
    'email' => '18229944342',
    'role' => 'user',
    'dir' => '["\\u674e\\u5a01"]',
    'quota' => '100',
  ),
  48 => 
  array (
    'name' => 'yanxia',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木卓越班(土木桥梁)',
    'pass' => '$1$yDP6ixUu$os4VGYXum9xrO6yE28ZYt0',
    'email' => '13319539782',
    'role' => 'user',
    'dir' => '["yanxia"]',
    'quota' => '100',
  ),
  49 => 
  array (
    'name' => 'Wfen',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '给排水科学与工程',
    'pass' => '$1$NUYO4P5M$d4BFKm6ZUsMfioS1.6vXg0',
    'email' => '18273171537',
    'role' => 'user',
    'dir' => '["Wfen"]',
    'quota' => '100',
  ),
  50 => 
  array (
    'name' => 'Alone',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(土建)',
    'pass' => '$1$eaFpRq6H$ZRur0G2OPZC/4vu8srEqZ1',
    'email' => '18773708831',
    'role' => 'user',
    'dir' => '["Alone"]',
    'quota' => '100',
  ),
  51 => 
  array (
    'name' => 'a2333',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$BK5ZRs7b$zdmJ85BS7vnNp4gEJDPic0',
    'email' => '15574924637',
    'role' => 'user',
    'dir' => '["a2333"]',
    'quota' => '100',
  ),
  52 => 
  array (
    'name' => 'yaoxuan',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '数学与应用数学',
    'pass' => '$1$rIGJw1cc$FN.lYqe04lf3MRdTAi.wV.',
    'email' => '18229763724',
    'role' => 'user',
    'dir' => '["yaoxuan"]',
    'quota' => '100',
  ),
  53 => 
  array (
    'name' => 'a110',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子科学与技术',
    'pass' => '$1$V05HZO1t$b88p41b2hDpsWoXksa3ra.',
    'email' => '17673639614',
    'role' => 'user',
    'dir' => '["a110"]',
    'quota' => '100',
  ),
  54 => 
  array (
    'name' => 'suzy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '生物工程',
    'pass' => '$1$UHQ5Lx1P$n5fp31h952a8fOk.jaSZx.',
    'email' => '18229937378',
    'role' => 'user',
    'dir' => '["suzy"]',
    'quota' => '100',
  ),
  55 => 
  array (
    'name' => 'ggyy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$9str3k7o$0iuRfp1p2STC2XKd/YwY4.',
    'email' => '15388064538',
    'role' => 'user',
    'dir' => '["ggyy"]',
    'quota' => '100',
  ),
  56 => 
  array (
    'name' => 'bzz',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '国际经济与贸易',
    'pass' => '$1$eg1rz45X$YnSeVO5BAzTAMKXwBK5iz.',
    'email' => '15574853349',
    'role' => 'user',
    'dir' => '["bzz"]',
    'quota' => '100',
  ),
  57 => 
  array (
    'name' => 'yn1998',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '材料成型及控制工程',
    'pass' => '$1$A4x9RA3a$uwcP/0dDc3Mp3X8rpCB/M0',
    'email' => '15367926639',
    'role' => 'user',
    'dir' => '["yn1998"]',
    'quota' => '100',
  ),
  58 => 
  array (
    'name' => '柳叶青青',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$54D4zkys$c7OTu47snq7n01R1gz4IR/',
    'email' => '15717509076',
    'role' => 'user',
    'dir' => '["\\u67f3\\u53f6\\u9752\\u9752"]',
    'quota' => '100',
  ),
  59 => 
  array (
    'name' => 'morono',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$UTdE3HlH$E4Due9Lym4LlmA61dOnyc0',
    'email' => '18874266364',
    'role' => 'user',
    'dir' => '["morono"]',
    'quota' => '100',
  ),
  61 => 
  array (
    'name' => 'yt980170995',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化(工程机械)',
    'pass' => '$1$071ZurIn$YWw2fq1CpG70.RXKwkg1B0',
    'email' => '17378117279',
    'role' => 'user',
    'dir' => '["yt980170995"]',
    'quota' => '100',
  ),
  62 => 
  array (
    'name' => '小A',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(土建)',
    'pass' => '$1$MNFM9PrB$M1vcmZD0MrCJdxqRG7oIj.',
    'email' => '15364070119',
    'role' => 'user',
    'dir' => '["\\u5c0fA"]',
    'quota' => '100',
  ),
  63 => 
  array (
    'name' => 'chiven',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '软件工程',
    'pass' => '$1$tCXjWp4e$v7ghdhd2CGJIc1gaaiceD1',
    'email' => '18507318032',
    'role' => 'user',
    'dir' => '["chiven"]',
    'quota' => '100',
  ),
  64 => 
  array (
    'name' => 'Dkny',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '食品科学与工程',
    'pass' => '$1$CDNgxog2$Ou1JMOGMAW6o2lcn0m/a20',
    'email' => '18473052999',
    'role' => 'user',
    'dir' => '["Dkny"]',
    'quota' => '100',
  ),
  65 => 
  array (
    'name' => 'twq1158969437',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$FIz22mg4$HAkNm85q50D0ay0NInaM2/',
    'email' => '18774815864',
    'role' => 'user',
    'dir' => '["twq1158969437"]',
    'quota' => '100',
  ),
  66 => 
  array (
    'name' => 'ZXY123',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$YomV3eHy$FtrdzADW1SE7e76dkQUYe/',
    'email' => '13549663529',
    'role' => 'user',
    'dir' => '["ZXY123"]',
    'quota' => '100',
  ),
  67 => 
  array (
    'name' => 'wyj4194',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$SB4uGv36$ftFEb7Pr0kOY1Bm6JXwjl/',
    'email' => '18684889726',
    'role' => 'user',
    'dir' => '["wyj4194"]',
    'quota' => '100',
  ),
  68 => 
  array (
    'name' => '李良虎',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$0hR21V8L$Oxg3vgtwSEniQ9JJ//b/31',
    'email' => '15655809551',
    'role' => 'user',
    'dir' => '["\\u674e\\u826f\\u864e"]',
    'quota' => '100',
  ),
  69 => 
  array (
    'name' => 'mgz25515',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '计算机科学与技术',
    'pass' => '$1$A8FKGC0v$K8HE8gropqGkXqenPb8nA0',
    'email' => '18374974532',
    'role' => 'user',
    'dir' => '["mgz25515"]',
    'quota' => '100',
  ),
  70 => 
  array (
    'name' => 'marvelousfyt',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '应用统计学',
    'pass' => '$1$SUp0t7BF$o7uOsxKLbrsyTD6ubBcYj0',
    'email' => '18774942918',
    'role' => 'user',
    'dir' => '["marvelousfyt"]',
    'quota' => '100',
  ),
  71 => 
  array (
    'name' => 'QIu',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$VFCanzVk$QinnzhBEetfteMXYNdnXy.',
    'email' => '18711801323',
    'role' => 'user',
    'dir' => '["QIu"]',
    'quota' => '100',
  ),
  72 => 
  array (
    'name' => 'bafen',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '交通运输类',
    'pass' => '$1$2oHMrfKV$tq0SFyieAPnDS8.6d066m0',
    'email' => '18073210779',
    'role' => 'user',
    'dir' => '["bafen"]',
    'quota' => '100',
  ),
  73 => 
  array (
    'name' => 'wt123',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '车辆工程',
    'pass' => '$1$SGcrw0Mx$Uj.9aLj.zfNm0.bsDaio/.',
    'email' => '13077369917',
    'role' => 'user',
    'dir' => '["wt123"]',
    'quota' => '100',
  ),
  74 => 
  array (
    'name' => 'hfx879139',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '信息与计算科学',
    'pass' => '$1$b8M9SyV1$ienig5PZNgmi0C4tjefQ8/',
    'email' => '13319606297',
    'role' => 'user',
    'dir' => '["hfx879139"]',
    'quota' => '100',
  ),
  75 => 
  array (
    'name' => 'htszy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学卓越人才班',
    'pass' => '$1$HFS4w2AX$K.VQb/I1BdnPBbYXbf81./',
    'email' => '17775615013',
    'role' => 'user',
    'dir' => '["htszy"]',
    'quota' => '100',
  ),
  76 => 
  array (
    'name' => 'Bfate',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '土木工程(道路工程)',
    'pass' => '$1$e41YFEvF$MPIVVVnMugKrWodRMKloH0',
    'email' => '17608429395',
    'role' => 'user',
    'dir' => '["Bfate"]',
    'quota' => '100',
  ),
  77 => 
  array (
    'name' => 'Smallstars',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '水文与水资源工程',
    'pass' => '$1$vCQR7hAU$k7d0yL1LNgt4VL07GgReo1',
    'email' => '15308465357',
    'role' => 'user',
    'dir' => '["Smallstars"]',
    'quota' => '100',
  ),
  79 => 
  array (
    'name' => 'ljm',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$RSFqDDMT$byTqpA4jgXyz1Pshq4YIN/',
    'email' => '15574968239',
    'role' => 'user',
    'dir' => '["ljm"]',
    'quota' => '100',
  ),
  80 => 
  array (
    'name' => 'test',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '软件工程',
    'pass' => '$1$lnUmklMj$0c.wQL5RTwZjvwVR8wmN/0',
    'email' => '14718091233',
    'role' => 'user',
    'dir' => '["test"]',
    'quota' => '100',
  ),
  81 => 
  array (
    'name' => '艾海林',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '计算机科学与技术',
    'pass' => '$1$SMrbxyQp$R0CCXJEvfhQdM5pVLlsmd/',
    'email' => '18229952935',
    'role' => 'user',
    'dir' => '["\\u827e\\u6d77\\u6797"]',
    'quota' => '100',
  ),
  82 => 
  array (
    'name' => 'goki',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$8p00Ln20$VFcyUdzWSGll45XkBkA450',
    'email' => '17373158627',
    'role' => 'user',
    'dir' => '["goki"]',
    'quota' => '100',
  ),
  83 => 
  array (
    'name' => 'yuweiba',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '汽车服务工程',
    'pass' => '$1$haZmYaCb$Wh4KEOHoZryLXLRmsQbTk0',
    'email' => '15007444180',
    'role' => 'user',
    'dir' => '["yuweiba"]',
    'quota' => '100',
  ),
  84 => 
  array (
    'name' => 'HT1508497',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化',
    'pass' => '$1$aGx63Cbu$0P62VPO6IgTZrBo9Eka9H0',
    'email' => '15084975231',
    'role' => 'user',
    'dir' => '["HT1508497"]',
    'quota' => '100',
  ),
  85 => 
  array (
    'name' => 'lwh',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '能源与动力工程学院',
    'majorName' => '自动化(热工过程自动化)',
    'pass' => '$1$cIrhjLq0$z.5BUj0uDjNyGI2069xRO0',
    'email' => '17773232679',
    'role' => 'user',
    'dir' => '["lwh"]',
    'quota' => '100',
  ),
  86 => 
  array (
    'name' => 'zxy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '人力资源管理',
    'pass' => '$1$pxEDCcYW$Ks2m5Ufg4Q13X08SYM2jN1',
    'email' => '18229891194',
    'role' => 'user',
    'dir' => '["zxy"]',
    'quota' => '100',
  ),
  87 => 
  array (
    'name' => 'daiwenjing',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '人力资源管理',
    'pass' => '$1$PBNDXkpF$aBXAk1ob2OlPISVGICxyN/',
    'email' => '15379657300',
    'role' => 'user',
    'dir' => '["daiwenjing"]',
    'quota' => '100',
  ),
  88 => 
  array (
    'name' => 'jyz',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '环境工程',
    'pass' => '$1$xSAb5odf$gTGiWznVyE80VUQNqxXl01',
    'email' => '15211041346',
    'role' => 'user',
    'dir' => '["jyz"]',
    'quota' => '100',
  ),
  89 => 
  array (
    'name' => 'ghn',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '新闻学',
    'pass' => '$1$gOkgMzah$Gw2H1gvCvmzBFBe91jCbF1',
    'email' => '17375871253',
    'role' => 'user',
    'dir' => '["ghn"]',
    'quota' => '100',
  ),
  90 => 
  array (
    'name' => 'Chenl',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '设计艺术学院',
    'majorName' => '视觉传达设计',
    'pass' => '$1$OAHoEI0F$.DHc.i22sXMoqzFEY9h7k1',
    'email' => '15737470801',
    'role' => 'user',
    'dir' => '["Chenl"]',
    'quota' => '100',
  ),
  91 => 
  array (
    'name' => 'ghn0608',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '新闻学',
    'pass' => '$1$vg4dHKYV$P6p1fSWLzn5oGh0GfIF7b1',
    'email' => '15990280256',
    'role' => 'user',
    'dir' => '["ghn0608"]',
    'quota' => '100',
  ),
  92 => 
  array (
    'name' => 'ly13973286037',
    'isStudent' => '是',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$Ipf9Nceu$RykWI/uuqk6eT8rnqEGQe/',
    'email' => '13973289037',
    'role' => 'user',
    'dir' => '["ly13973286037"]',
    'quota' => '100',
  ),
  93 => 
  array (
    'name' => 'lnn',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$kSdoVVDd$5GyvNCOGG6o0bv/rWfiqU.',
    'email' => '18273181149',
    'role' => 'user',
    'dir' => '["lnn"]',
    'quota' => '100',
  ),
  94 => 
  array (
    'name' => 'cslg',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '信息与计算科学',
    'pass' => '$1$Sg7ohYgn$M/goJjAM84/wZ.lcaunDG.',
    'email' => '15273136028',
    'role' => 'user',
    'dir' => '["cslg"]',
    'quota' => '100',
  ),
  95 => 
  array (
    'name' => 'LX123456',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$k3YsT4a7$Vu7D4vBAxbNiCWQiSz8Bl.',
    'email' => '13648237203',
    'role' => 'user',
    'dir' => '["LX123456"]',
    'quota' => '100',
  ),
  96 => 
  array (
    'name' => 'RIVEN',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '轨道交通信号与控制',
    'pass' => '$1$BVBYhehG$OAKOQ5JjFhKEaaE6KORD81',
    'email' => '18229973433',
    'role' => 'user',
    'dir' => '["RIVEN"]',
    'quota' => '100',
  ),
  97 => 
  array (
    'name' => 'QQ1715288339',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$z6fuj5QZ$hnIxi8dev72vibOSJj/6E1',
    'email' => '18670666385',
    'role' => 'user',
    'dir' => '["QQ1715288339"]',
    'quota' => '100',
  ),
  98 => 
  array (
    'name' => 'lyiyayiya',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '材料成型及控制工程',
    'pass' => '$1$DJgsYqUh$4wSrz/ZaW.iSFqLlbtGbc1',
    'email' => '15574889540',
    'role' => 'user',
    'dir' => '["lyiyayiya"]',
    'quota' => '100',
  ),
  99 => 
  array (
    'name' => 'hzw',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '材料成型及控制工程',
    'pass' => '$1$1UZolfjO$Jkt5Tflwkt9vQ6/uc8p6q.',
    'email' => '18711628715',
    'role' => 'user',
    'dir' => '["hzw"]',
    'quota' => '100',
  ),
  100 => 
  array (
    'name' => 'wukevin',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化(机电)',
    'pass' => '$1$BLbJua0U$7HwySxgfdXKKRmz4WvvEI0',
    'email' => '15084963945',
    'role' => 'user',
    'dir' => '["wukevin"]',
    'quota' => '100',
  ),
  101 => 
  array (
    'name' => 'mary8510',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '车辆工程',
    'pass' => '$1$LBTsTinY$ON9Kff1whQrRNE7pZzi/00',
    'email' => '15717519196',
    'role' => 'user',
    'dir' => '["mary8510"]',
    'quota' => '100',
  ),
  102 => 
  array (
    'name' => 'yiye',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '应用化学',
    'pass' => '$1$cLkOmRQH$toPMf1xGMNI9RmTVrfJl4/',
    'email' => '18374800731',
    'role' => 'user',
    'dir' => '["yiye"]',
    'quota' => '100',
  ),
  103 => 
  array (
    'name' => 'abcd',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '交通运输类',
    'pass' => '$1$UaaAsS7J$WQt7ZYmhP4jazf0rC4sLc/',
    'email' => '15084942644',
    'role' => 'user',
    'dir' => '["abcd"]',
    'quota' => '100',
  ),
  104 => 
  array (
    'name' => 'hhn911',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$zTakrlDC$cL0CvYDs2rvZqOLuViv2k.',
    'email' => '15830655911',
    'role' => 'user',
    'dir' => '["hhn911"]',
    'quota' => '100',
  ),
  105 => 
  array (
    'name' => 'YoLa',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化',
    'pass' => '$1$q87SadGV$mLtdXJrNMOY.y4n6gqoAg/',
    'email' => '17673159524',
    'role' => 'user',
    'dir' => '["YoLa"]',
    'quota' => '100',
  ),
  106 => 
  array (
    'name' => 'hzy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$H8xdZn3L$tyukY/1RLQ9djM1KAv7Ih1',
    'email' => '17773493187',
    'role' => 'user',
    'dir' => '["hzy"]',
    'quota' => '100',
  ),
  107 => 
  array (
    'name' => 'jcj963210322',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$CKT8440r$2vWYeKx1eyxFckfPsunlX.',
    'email' => '18229955037',
    'role' => 'user',
    'dir' => '["jcj963210322"]',
    'quota' => '100',
  ),
  108 => 
  array (
    'name' => 'GRO',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '测绘工程',
    'pass' => '$1$9v80TrKh$DrRnwa6.PTumxTGV9dkNQ/',
    'email' => '15348412355',
    'role' => 'user',
    'dir' => '["GRO"]',
    'quota' => '100',
  ),
  109 => 
  array (
    'name' => 'brad',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '网络工程',
    'pass' => '$1$jeUWrv14$yqPgC4biYDs5KqOgYDpwi/',
    'email' => '17680157842',
    'role' => 'user',
    'dir' => '["brad"]',
    'quota' => '100',
  ),
  110 => 
  array (
    'name' => 'xiaomubai',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(土建)',
    'pass' => '$1$Avb633A6$RB4jquiI.wV4ox48sCPjZ.',
    'email' => '18774862168',
    'role' => 'user',
    'dir' => '["xiaomubai"]',
    'quota' => '100',
  ),
  111 => 
  array (
    'name' => 'Amy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '外国语学院',
    'majorName' => '英语(工程商务英语)',
    'pass' => '$1$IpwmToEh$ovFLxYhCv5pXaHYm0tr4w/',
    'email' => '14773226717',
    'role' => 'user',
    'dir' => '["Amy"]',
    'quota' => '100',
  ),
  112 => 
  array (
    'name' => 'yyy',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$tRff6QiI$2pz1q4UjR1FALW/VmwUgV/',
    'email' => '17873350203',
    'role' => 'user',
    'dir' => '["yyy"]',
    'quota' => '100',
  ),
  113 => 
  array (
    'name' => 'Peau',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '土木工程(道路工程)',
    'pass' => '$1$MpaU2aEf$0MjhrXqGQ1soC1vtPr2hv/',
    'email' => '15616125404',
    'role' => 'user',
    'dir' => '["Peau"]',
    'quota' => '100',
  ),
  114 => 
  array (
    'name' => 'lvjing',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '给排水科学与工程',
    'pass' => '$1$oGA27YRU$j7QQRxj1l1ZcPM123SQWH1',
    'email' => '15874833802',
    'role' => 'user',
    'dir' => '["lvjing"]',
    'quota' => '100',
  ),
  115 => 
  array (
    'name' => 'qqj15874288642',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$GvkWiKHA$zFJS7IUBee9ZBhXAeWlsR/',
    'email' => '15874288642',
    'role' => 'user',
    'dir' => '["qqj15874288642"]',
    'quota' => '100',
  ),
  116 => 
  array (
    'name' => 'yangminghui',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '材料科学与工程学院',
    'majorName' => '无机非金属材料工程',
    'pass' => '$1$Hfg4PTLG$1MBAlKC61erwoc3w15tA4.',
    'email' => '15367929289',
    'role' => 'user',
    'dir' => '["yangminghui"]',
    'quota' => '100',
  ),
  117 => 
  array (
    'name' => 'lsx111',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '港口航道与海岸工程',
    'pass' => '$1$nDTYzXEu$OpyL4vAYd6GTZg9YsU99p1',
    'email' => '15211041356',
    'role' => 'user',
    'dir' => '["lsx111"]',
    'quota' => '100',
  ),
  118 => 
  array (
    'name' => 'Shavonne',
    'isStudent' => '是',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$GiuPmV1B$Ye4lOdKVK.f.onMCWIctP1',
    'email' => '18569406329',
    'role' => 'user',
    'dir' => '["Shavonne"]',
    'quota' => '100',
  ),
  119 => 
  array (
    'name' => 'xjy0731',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$xPQokZ3e$QSVxYuxeV58JEFNei3LsT1',
    'email' => '13787281533',
    'role' => 'user',
    'dir' => '["xjy0731"]',
    'quota' => '100',
  ),
  120 => 
  array (
    'name' => 'hero',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$xQjKZ2kf$16Oyx/S3rG8tnpp9UEXK.0',
    'email' => '13739095182',
    'role' => 'user',
    'dir' => '["hero"]',
    'quota' => '100',
  ),
  121 => 
  array (
    'name' => 'loao',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$eMX4UvW9$VYSG/cEgYh1tB8WyMzSD/.',
    'email' => '18374951231',
    'role' => 'user',
    'dir' => '["loao"]',
    'quota' => '100',
  ),
  122 => 
  array (
    'name' => 'lalala',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$SBcBSmag$HcC06et9y/F281wXKnYE41',
    'email' => '15274919215',
    'role' => 'user',
    'dir' => '["lalala"]',
    'quota' => '100',
  ),
  123 => 
  array (
    'name' => 'cly',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '人力资源管理',
    'pass' => '$1$Mb8vcQJp$vTgGs/eou2u6nKKcurow.1',
    'email' => '13142126650',
    'role' => 'user',
    'dir' => '["cly"]',
    'quota' => '100',
  ),
  124 => 
  array (
    'name' => 'GSX',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$w02Cw78e$BfROcgvu391tN7lF3uKG8.',
    'email' => '15286065899',
    'role' => 'user',
    'dir' => '["GSX"]',
    'quota' => '100',
  ),
  125 => 
  array (
    'name' => 'Oohalo',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '轨道交通信号与控制',
    'pass' => '$1$BuM2p7Vv$HZQNIKzw4epoSKqPHdl.b/',
    'email' => '15580914720',
    'role' => 'user',
    'dir' => '["Oohalo"]',
    'quota' => '100',
  ),
  126 => 
  array (
    'name' => 'sfj',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '材料科学与工程学院',
    'majorName' => '无机非金属材料工程（建筑材料）',
    'pass' => '$1$nhciXIs1$vSKIUOGAs5gQ2yhpqYWD1/',
    'email' => '15115652821',
    'role' => 'user',
    'dir' => '["sfj"]',
    'quota' => '100',
  ),
  127 => 
  array (
    'name' => 'liu',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木卓越班(土木桥梁)',
    'pass' => '$1$BijdNiXj$1JmnjqkKhL03Pd53o0Nyl.',
    'email' => '15580044896',
    'role' => 'user',
    'dir' => '["liu"]',
    'quota' => '100',
  ),
  128 => 
  array (
    'name' => 'zyl',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$FytkXBkF$OWTFX5GSPGTRvrN6RlLAy.',
    'email' => '15362437823',
    'role' => 'user',
    'dir' => '["zyl"]',
    'quota' => '100',
  ),
  129 => 
  array (
    'name' => 'Asd',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$FDrrUlB6$xhO8JdMRABnBSuVlGCRu81',
    'email' => '18229896190',
    'role' => 'user',
    'dir' => '["Asd"]',
    'quota' => '100',
  ),
  130 => 
  array (
    'name' => 'Pedro',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '轨道交通信号与控制',
    'pass' => '$1$TY4FRKpw$pv.6wwEX.NA1orGcJ1fIK0',
    'email' => '18273194439',
    'role' => 'user',
    'dir' => '["Pedro"]',
    'quota' => '100',
  ),
  131 => 
  array (
    'name' => 'wyk',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '光电信息科学与工程',
    'pass' => '$1$KmQ6aMI2$GB8fm8FLJXt.Vdu5r4Ym40',
    'email' => '18229949250',
    'role' => 'user',
    'dir' => '["wyk"]',
    'quota' => '100',
  ),
  132 => 
  array (
    'name' => 'super',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化(机电)',
    'pass' => '$1$pR1sBZoL$V/jBHO0zIf9TkATc1Tk8.1',
    'email' => '13077308839',
    'role' => 'user',
    'dir' => '["super"]',
    'quota' => '100',
  ),
  133 => 
  array (
    'name' => 'xucailing',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '生物工程',
    'pass' => '$1$zajiHDqr$vYsoh0zs3cRG6rjn2l0ZJ.',
    'email' => '13786147347',
    'role' => 'user',
    'dir' => '["xucailing"]',
    'quota' => '100',
  ),
  134 => 
  array (
    'name' => 'chanbaekni',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '生物工程',
    'pass' => '$1$O7rkzBdJ$PisqSdms0xZ4HgjsHF/BX/',
    'email' => '15273132529',
    'role' => 'user',
    'dir' => '["chanbaekni"]',
    'quota' => '100',
  ),
  135 => 
  array (
    'name' => 'feng',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '生物工程',
    'pass' => '$1$L8JP4QXn$FJIJm.2gh09walYLaVFvP1',
    'email' => '18374650479',
    'role' => 'user',
    'dir' => '["feng"]',
    'quota' => '100',
  ),
  136 => 
  array (
    'name' => 'momoxiaohuihui',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$KE4gKhtI$txD3m688gSJIHlCInX0EZ.',
    'email' => '15073164327',
    'role' => 'user',
    'dir' => '["momoxiaohuihui"]',
    'quota' => '100',
  ),
  137 => 
  array (
    'name' => 'sky',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(建筑工程)',
    'pass' => '$1$vS3MCSKi$SchTmFTPS1aogOaS1g2sN/',
    'email' => '18229807121',
    'role' => 'user',
    'dir' => '["sky"]',
    'quota' => '100',
  ),
  138 => 
  array (
    'name' => 'jessaiu',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '人力资源管理',
    'pass' => '$1$Kcgfnz9P$ADuPoU1iGJGU5WIjwRJwx0',
    'email' => '15080886515',
    'role' => 'user',
    'dir' => '["jessaiu"]',
    'quota' => '100',
  ),
  139 => 
  array (
    'name' => 'Taurus',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化(工程机械)',
    'pass' => '$1$R5If9hhV$sjKE2cAPs8Ki5Abwd4slQ/',
    'email' => '15855126823',
    'role' => 'user',
    'dir' => '["Taurus"]',
    'quota' => '100',
  ),
  140 => 
  array (
    'name' => 'lly',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$zgN81vKN$YYaa32lsadSOHjK/LM5g71',
    'email' => '18130481353',
    'role' => 'user',
    'dir' => '["lly"]',
    'quota' => '100',
  ),
  141 => 
  array (
    'name' => 'liud',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '港口航道与海岸工程',
    'pass' => '$1$KRdjx9DZ$jP826UY7t185OZarPWSYK0',
    'email' => '18855440257',
    'role' => 'user',
    'dir' => '["liud"]',
    'quota' => '100',
  ),
  142 => 
  array (
    'name' => 'mc970489022',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$M9HHHZ2v$zWCTnxEHv8bkZRFVKIKKx1',
    'email' => '17608413944',
    'role' => 'user',
    'dir' => '["mc970489022"]',
    'quota' => '100',
  ),
  143 => 
  array (
    'name' => 'ljh',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '汉语言文学',
    'pass' => '$1$0eQBNQj7$MZUL9rnAyGAdCq4TVDWbT/',
    'email' => '15367950679',
    'role' => 'user',
    'dir' => '["ljh"]',
    'quota' => '100',
  ),
  144 => 
  array (
    'name' => 'XK1140',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '信息管理与信息系统',
    'pass' => '$1$vxyDFBPs$B9DfaProzUETcLSHDQgzm/',
    'email' => '13755053913',
    'role' => 'user',
    'dir' => '["XK1140"]',
    'quota' => '100',
  ),
  145 => 
  array (
    'name' => 'ykwsmile',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '外国语学院',
    'majorName' => '翻译',
    'pass' => '$1$9wPqzppd$cQ/2dpYgQxTrribGi0/tJ0',
    'email' => '15116327413',
    'role' => 'user',
    'dir' => '["ykwsmile"]',
    'quota' => '100',
  ),
  146 => 
  array (
    'name' => 'phk747299570',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '轨道交通信号与控制',
    'pass' => '$1$bWYMY4XV$uZJ99blhibAWcjyNWOy4b0',
    'email' => '15581667401',
    'role' => 'user',
    'dir' => '["phk747299570"]',
    'quota' => '100',
  ),
  147 => 
  array (
    'name' => 'Yrq',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$LhgPWSKV$aZDRWfhf2ndtEV/pIkJtl1',
    'email' => '18229963782',
    'role' => 'user',
    'dir' => '["Yrq"]',
    'quota' => '100',
  ),
  148 => 
  array (
    'name' => 'wjx',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '土木工程卓越人才班',
    'pass' => '$1$BnG6SgWh$Q.d0ktilcKclAq1GJ06QW/',
    'email' => '13397492984',
    'role' => 'user',
    'dir' => '["wjx"]',
    'quota' => '100',
  ),
  149 => 
  array (
    'name' => 'fzy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$HyTdTgOX$OkAoAHK5IUQP8767Qyayw.',
    'email' => '18374892726',
    'role' => 'user',
    'dir' => '["fzy"]',
    'quota' => '100',
  ),
  150 => 
  array (
    'name' => 'sx1787749311',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '法学（工程法学）',
    'pass' => '$1$UjHi1rkM$Uy0LO1QQwNm68Nvhqg/mo0',
    'email' => '18390579924',
    'role' => 'user',
    'dir' => '["sx1787749311"]',
    'quota' => '100',
  ),
  151 => 
  array (
    'name' => 'yjlws',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$ilLpD4kM$Y9Wz64XobPxSCfH9cbh/G/',
    'email' => '13973753837',
    'role' => 'user',
    'dir' => '["yjlws"]',
    'quota' => '100',
  ),
  152 => 
  array (
    'name' => 'lzq',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$mp88eB5Y$pPg1uVqOwimwhQC/sLmGO.',
    'email' => '15574989091',
    'role' => 'user',
    'dir' => '["lzq"]',
    'quota' => '100',
  ),
  153 => 
  array (
    'name' => 'tang',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$sW5z1kx3$AdKpc8jNxoPSki79ajJqN1',
    'email' => '13037318565',
    'role' => 'user',
    'dir' => '["tang"]',
    'quota' => '100',
  ),
  154 => 
  array (
    'name' => 'LJY',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$t0aoAP61$.dLlAh2G8xwsfm/ksyu5U0',
    'email' => '13327212830',
    'role' => 'user',
    'dir' => '["LJY"]',
    'quota' => '100',
  ),
  155 => 
  array (
    'name' => 'tangjieyu',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '环境工程',
    'pass' => '$1$XyL6qA2a$r0FpmjIMtMoZp9fKC/qDZ.',
    'email' => '15074899935',
    'role' => 'user',
    'dir' => '["tangjieyu"]',
    'quota' => '100',
  ),
  156 => 
  array (
    'name' => 'slyvia',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '信息管理与信息系统',
    'pass' => '$1$OfvRRoeV$3GPlEYNnKArW.EEdv0rUo/',
    'email' => '18229855366',
    'role' => 'user',
    'dir' => '["slyvia"]',
    'quota' => '100',
  ),
  157 => 
  array (
    'name' => 'ZTCYYW',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '能源与动力工程学院',
    'majorName' => '能源与动力工程',
    'pass' => '$1$mUHhqChe$ovFJ4ZPcxT/qaRXrsevRO1',
    'email' => '18711108512',
    'role' => 'user',
    'dir' => '["ZTCYYW"]',
    'quota' => '100',
  ),
  158 => 
  array (
    'name' => 'huang',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '水电卓越班',
    'pass' => '$1$5LTVzsry$AHhzhMxmzK9LtYp4ZjYy41',
    'email' => '17608420536',
    'role' => 'user',
    'dir' => '["huang"]',
    'quota' => '100',
  ),
  159 => 
  array (
    'name' => 'Unicorn',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '化学与生物工程学院',
    'majorName' => '化工与制药类',
    'pass' => '$1$n3PrUDlb$PBEcQ1LQXDy0uE46XBjFJ1',
    'email' => '15873212922',
    'role' => 'user',
    'dir' => '["Unicorn"]',
    'quota' => '100',
  ),
  160 => 
  array (
    'name' => 'lqynimqj',
    'isStudent' => '否',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$OjQlTiB2$1P9uGrb308M361I4OHChD1',
    'email' => '18173855183',
    'role' => 'user',
    'dir' => '["lqynimqj"]',
    'quota' => '100',
  ),
  161 => 
  array (
    'name' => 'w3980435',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(土建)',
    'pass' => '$1$jchkghNn$vIDR0tCXB/DSZJnSiAmcX0',
    'email' => '15292081207',
    'role' => 'user',
    'dir' => '["w3980435"]',
    'quota' => '100',
  ),
  162 => 
  array (
    'name' => 'MoCuishle',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '汽车服务工程',
    'pass' => '$1$ZIq0oXuB$2d.WG5P.Yk06xIyvZ1EPQ/',
    'email' => '18874117636',
    'role' => 'user',
    'dir' => '["MoCuishle"]',
    'quota' => '100',
  ),
  163 => 
  array (
    'name' => 'Anzhiyang',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电气工程及其自动化',
    'pass' => '$1$7EqgZTM9$PZ2SZthfyVuzAQSjgpZTk/',
    'email' => '18374963598',
    'role' => 'user',
    'dir' => '["Anzhiyang"]',
    'quota' => '100',
  ),
  164 => 
  array (
    'name' => 'WHITE',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$NWCkeqAS$6foXOfcLRJwMJTE3Z7O8L.',
    'email' => '13142060343',
    'role' => 'user',
    'dir' => '["WHITE"]',
    'quota' => '100',
  ),
  165 => 
  array (
    'name' => 'LHN',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '自动化（工业自动化）',
    'pass' => '$1$E294tE2A$SGwN8V/m1Rn6b5rm/FXqF0',
    'email' => '17375871324',
    'role' => 'user',
    'dir' => '["LHN"]',
    'quota' => '100',
  ),
  166 => 
  array (
    'name' => 'csy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '电气与信息工程学院',
    'majorName' => '电子信息工程',
    'pass' => '$1$Ny0IRz2J$lZPiujiRsWYpQWiHKoLzM/',
    'email' => '13873253166',
    'role' => 'user',
    'dir' => '["csy"]',
    'quota' => '100',
  ),
  167 => 
  array (
    'name' => 'wkk',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '国际经济与贸易',
    'pass' => '$1$cgr1pmsb$4YUiD.ZUJgTDqTKmyoyOh0',
    'email' => '18569458015',
    'role' => 'user',
    'dir' => '["wkk"]',
    'quota' => '100',
  ),
  168 => 
  array (
    'name' => 'LJH',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$Knu2yIR9$gYt8kVbZlUZ92x/bMnYr5/',
    'email' => '18773167513',
    'role' => 'user',
    'dir' => '["LJH"]',
    'quota' => '100',
  ),
  169 => 
  array (
    'name' => 'Q123',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '测绘工程',
    'pass' => '$1$yeWAF8FQ$5aL3CZ5iM7.eyDZvRcrkQ/',
    'email' => '15574944018',
    'role' => 'user',
    'dir' => '["Q123"]',
    'quota' => '100',
  ),
  170 => 
  array (
    'name' => 'ccvv',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '财务管理',
    'pass' => '$1$t0ElpO4E$1jLofUW1EW5AEWisk0a96/',
    'email' => '18163959986',
    'role' => 'user',
    'dir' => '["ccvv"]',
    'quota' => '100',
  ),
  171 => 
  array (
    'name' => 'LYF',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '软件工程',
    'pass' => '$1$xupxTnBl$NGO5Xd2eJJaBzXExwsAB41',
    'email' => '18174450274',
    'role' => 'user',
    'dir' => '["LYF"]',
    'quota' => '100',
  ),
  172 => 
  array (
    'name' => 'zzzzzz',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '能源与动力工程学院',
    'majorName' => '能源与动力工程',
    'pass' => '$1$0dU1qCk3$4KtD9bHLS49KBHLWR6Y2d1',
    'email' => '18270065082',
    'role' => 'user',
    'dir' => '["zzzzzz"]',
    'quota' => '100',
  ),
  173 => 
  array (
    'name' => 'ddd3d',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '金融学',
    'pass' => '$1$JVnEkU9h$AW6vp2rGBOalm6DItZizb0',
    'email' => '17674641454',
    'role' => 'user',
    'dir' => '["ddd3d"]',
    'quota' => '100',
  ),
  174 => 
  array (
    'name' => 'Jin',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '交通运输(管交)',
    'pass' => '$1$lnUmklMj$0c.wQL5RTwZjvwVR8wmN/0',
    'email' => '15386466944',
    'role' => 'user',
    'dir' => '["Jin"]',
    'quota' => '100',
  ),
  175 => 
  array (
    'name' => 'liuliu',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$hgP6Kc07$ML5i1ZnFiNUaJj.189aL20',
    'email' => '18273118841',
    'role' => 'user',
    'dir' => '["liuliu"]',
    'quota' => '100',
  ),
  176 => 
  array (
    'name' => 'AliceCheung',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$mpHoT045$9Qcpkd8IBip.RbHp/3kj0.',
    'email' => '13026838892',
    'role' => 'user',
    'dir' => '["AliceCheung"]',
    'quota' => '100',
  ),
  177 => 
  array (
    'name' => 'garkey',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '物理与电子科学学院',
    'majorName' => '电子信息科学与技术',
    'pass' => '$1$4tSKoNct$yS.22OTBoisCEtivt.nP3.',
    'email' => '18970612963',
    'role' => 'user',
    'dir' => '["garkey"]',
    'quota' => '100',
  ),
  178 => 
  array (
    'name' => 'i1492059196',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '通信工程',
    'pass' => '$1$Kt5nXXvf$VOVvv2a41KZ9usNMV8uH7.',
    'email' => '18774942270',
    'role' => 'user',
    'dir' => '["i1492059196"]',
    'quota' => '100',
  ),
  179 => 
  array (
    'name' => 'xjy4760510',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(桥梁工程)',
    'pass' => '$1$tBEHh4qe$pT6Xtam5BBNdLW9YGOhwg.',
    'email' => '13786193275',
    'role' => 'user',
    'dir' => '["xjy4760510"]',
    'quota' => '100',
  ),
  180 => 
  array (
    'name' => 'wyt123',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '财务管理',
    'pass' => '$1$W7f5VGh7$qGhCjHTwiqEfirlQqBMje/',
    'email' => '18373142572',
    'role' => 'user',
    'dir' => '["wyt123"]',
    'quota' => '100',
  ),
  181 => 
  array (
    'name' => 'wy247449971',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '汉语言文学',
    'pass' => '$1$b6rQUloy$9n9wcPLr9YPgxtAYMY3Rs.',
    'email' => '15575924244',
    'role' => 'user',
    'dir' => '["wy247449971"]',
    'quota' => '100',
  ),
  182 => 
  array (
    'name' => 'xie',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '汽车与机械工程学院',
    'majorName' => '机械设计制造及其自动化',
    'pass' => '$1$CO1bUy4Z$DMsE.GiczKSLsUKTdNnbq0',
    'email' => '18390876242',
    'role' => 'user',
    'dir' => '["xie"]',
    'quota' => '100',
  ),
  183 => 
  array (
    'name' => 'Chloe',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$GxYkVgbD$WiaioOAGEq0LB25/dWm770',
    'email' => '13975839272',
    'role' => 'user',
    'dir' => '["Chloe"]',
    'quota' => '100',
  ),
  184 => 
  array (
    'name' => 'tuzhi',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '给排水科学与工程',
    'pass' => '$1$hh5yp86i$6Cm0dD8UcJZh29jPs0osZ1',
    'email' => '15211015813',
    'role' => 'user',
    'dir' => '["tuzhi"]',
    'quota' => '100',
  ),
  185 => 
  array (
    'name' => 'sdpshimeinv',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '计算机与通信工程学院',
    'majorName' => '计算机科学与技术',
    'pass' => '$1$NXHdnMi9$rIawUnWsNaetxVjGMIIQj0',
    'email' => '18229815891',
    'role' => 'user',
    'dir' => '["sdpshimeinv"]',
    'quota' => '100',
  ),
  186 => 
  array (
    'name' => 'SHUILI',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '给排水科学与工程',
    'pass' => '$1$B3w32Q6m$TapP1fVdMd4q3AjswExOJ/',
    'email' => '17673091642',
    'role' => 'user',
    'dir' => '["SHUILI"]',
    'quota' => '100',
  ),
  187 => 
  array (
    'name' => 'cy2934283546',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '数学与应用数学',
    'pass' => '$1$qkjJLhRn$7N/yh5OM5ifELX6iIiN3l1',
    'email' => '15173827616',
    'role' => 'user',
    'dir' => '["cy2934283546"]',
    'quota' => '100',
  ),
  188 => 
  array (
    'name' => 'zeb1104081687',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '数学与统计学院',
    'majorName' => '数学与应用数学',
    'pass' => '$1$hRcZncQd$hdxxNWAQa/7.PnUttcJhO0',
    'email' => '13157816628',
    'role' => 'user',
    'dir' => '["zeb1104081687"]',
    'quota' => '100',
  ),
  189 => 
  array (
    'name' => 'ZQZQ',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '工程管理',
    'pass' => '$1$BtIRlTTz$pqK0Vj1MmYmwsKmdaiNe.1',
    'email' => '13279927089',
    'role' => 'user',
    'dir' => '["ZQZQ"]',
    'quota' => '100',
  ),
  190 => 
  array (
    'name' => 'hys',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '物流工程',
    'pass' => '$1$rt0E66bs$6.cjDCnD6r4vCRyO3bWgt0',
    'email' => '15116423802',
    'role' => 'user',
    'dir' => '["hys"]',
    'quota' => '100',
  ),
  191 => 
  array (
    'name' => 'CYANQI',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '国际经济与贸易',
    'pass' => '$1$fUpIoB0m$TovTvqWi3eFSl4xWK0Cav0',
    'email' => '17307404193',
    'role' => 'user',
    'dir' => '["CYANQI"]',
    'quota' => '100',
  ),
  192 => 
  array (
    'name' => 'guda',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$xGXw1a7O$Nckm3IJ/yQ.YU4kxQq8E.0',
    'email' => '17307404008',
    'role' => 'user',
    'dir' => '["guda"]',
    'quota' => '100',
  ),
  193 => 
  array (
    'name' => 'ZYH',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '法学（工程法学）',
    'pass' => '$1$Reo2GjJY$7ZO7s2yX/oSIjDChU1oEA0',
    'email' => '18373146266',
    'role' => 'user',
    'dir' => '["ZYH"]',
    'quota' => '100',
  ),
  194 => 
  array (
    'name' => 'Jennifer',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '金融学',
    'pass' => '$1$n3CbU31V$KkjSmmEJLmBluqauCcP4r0',
    'email' => '18374973794',
    'role' => 'user',
    'dir' => '["Jennifer"]',
    'quota' => '100',
  ),
  195 => 
  array (
    'name' => 'wxy1216dandan',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '水利工程学院',
    'majorName' => '港口航道与海岸工程',
    'pass' => '$1$P2m49jek$IY5b9BtjX1NHMQh/k3QR81',
    'email' => '15116122630',
    'role' => 'user',
    'dir' => '["wxy1216dandan"]',
    'quota' => '100',
  ),
  196 => 
  array (
    'name' => 'shawolmeu',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '设计艺术学院',
    'majorName' => '产品设计',
    'pass' => '$1$YojIjgr8$0G3Cg8Z9ySZdHTFNmeaRD0',
    'email' => '13235953776',
    'role' => 'user',
    'dir' => '["shawolmeu"]',
    'quota' => '100',
  ),
  197 => 
  array (
    'name' => 'zmlzml',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '交通运输工程学院',
    'majorName' => '土木工程卓越人才班',
    'pass' => '$1$8qI8DQAF$PBPLVpGqkysg9reWXSiUv0',
    'email' => '15211072135',
    'role' => 'user',
    'dir' => '["zmlzml"]',
    'quota' => '100',
  ),
  198 => 
  array (
    'name' => 'giao',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '设计艺术学院',
    'majorName' => '环境设计',
    'pass' => '$1$OjlPMjK5$A8n9lMG0P1/DWyJDkpB6A0',
    'email' => '17670746684',
    'role' => 'user',
    'dir' => '["giao"]',
    'quota' => '100',
  ),
  199 => 
  array (
    'name' => 'CGY',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '会计学',
    'pass' => '$1$162yZ8fo$Km91Ta90QZ1/FL0VzqNL.0',
    'email' => '18820720375',
    'role' => 'user',
    'dir' => '["CGY"]',
    'quota' => '100',
  ),
  200 => 
  array (
    'name' => 'hyy',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '土木工程(建筑工程)',
    'pass' => '$1$SCrNg7nA$Kv4UgsvvgIMJl2hS/zkB00',
    'email' => '15387301892',
    'role' => 'user',
    'dir' => '["hyy"]',
    'quota' => '100',
  ),
  201 => 
  array (
    'name' => 'yy0922',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '经济与管理学院',
    'majorName' => '金融学',
    'pass' => '$1$Nhf32jm4$aw.twICMvvyAV/B39dR6g.',
    'email' => '15324051579',
    'role' => 'user',
    'dir' => '["yy0922"]',
    'quota' => '100',
  ),
  202 => 
  array (
    'name' => 'yuan',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '汉语言文学',
    'pass' => '$1$BCcG7WsI$3Mce7KXQTur2IvwemFk.i1',
    'email' => '13507459549',
    'role' => 'user',
    'dir' => '["yuan"]',
    'quota' => '100',
  ),
  203 => 
  array (
    'name' => 'pyd125966',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '文法学院',
    'majorName' => '汉语言文学',
    'pass' => '$1$idRhrvMI$mx9.TNpsnkVpkMyyhEMIx.',
    'email' => '18229906224',
    'role' => 'user',
    'dir' => '["pyd125966"]',
    'quota' => '100',
  ),
  204 => 
  array (
    'name' => 'pzb2698855478',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '设计艺术学院',
    'majorName' => '数字媒体艺术',
    'pass' => '$1$yioFyH65$HR6apMhBjVexl/T9IxCkE.',
    'email' => '18574380322',
    'role' => 'user',
    'dir' => '["pzb2698855478"]',
    'quota' => '100',
  ),
  205 => 
  array (
    'name' => 'qlh03094935',
    'isStudent' => '是',
    'schoolName' => '长沙理工大学',
    'academyName' => '土木工程学院',
    'majorName' => '工程力学',
    'pass' => '$1$VtYsbnTf$vF1rPt/8kiabFfGYsVsRj.',
    'email' => '18374991525',
    'role' => 'user',
    'dir' => '["qlh03094935"]',
    'quota' => '100',
  ),
  206 => 
  array (
    'name' => '17388939295',
    'isStudent' => '是',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$JAYhVaYO$xhzCtdiT.qAXLBECM8SRN0',
    'email' => '17388939295',
    'role' => 'user',
    'dir' => '["17388939295"]',
    'quota' => '100',
  ),
  207 => 
  array (
    'name' => '18551687840',
    'isStudent' => '是',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$pmC8vE1V$MIzQAAalxVQwevgv960Ih1',
    'email' => '18551687840',
    'role' => 'user',
    'dir' => '["18551687840"]',
    'quota' => '100',
  ),
  208 => 
  array (
    'name' => '1867037983',
    'isStudent' => '是',
    'schoolName' => '0',
    'academyName' => '0',
    'majorName' => '0',
    'pass' => '$1$IEcUuDl5$w6EcsIl3LYx3m2YHBH6Lz/',
    'email' => '1867037983',
    'role' => 'user',
    'dir' => '["1867037983"]',
    'quota' => '100',
  ),
);
